[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.mypy]
ignore_missing_imports = true

[tool.poetry]
name = "keyword-extractor"
version = "0.1.0"
description = "Extract keywords from documents with spaCy and scikit-learn"
authors = ["Scott Stevenson <scott@stevenson.io>"]
license = "ISC"

[tool.poetry.scripts]
keyword-extractor = "keyword_extractor:main"

[tool.poetry.dependencies]
python = "^3.9"
scikit-learn = "^1.1"
spacy = "^3.3.1"
tabulate = "^0.8.10"

[tool.poetry.dev-dependencies]
black = "^22.6"
flake8 = "^4.0.1"
isort = "^5.10.1"
mypy = "^0.961"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
nox = "^2022.1.7"
types-tabulate = "^0.8.11"
pyupgrade = "^2.32.1"
flake8-pytest-style = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
