name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python3 -m pip install coverage poetry
          poetry install
          poetry run python3 -m spacy download en_core_web_sm

      - name: Run checks
        run: poetry run poe check

      - name: Create coverage report
        run: coverage lcov

      - name: Upload coverage report
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./coverage.lcov
          delete-old-comments: true
